---
- name: OpenShift Auto Recovery
  hosts: all
  match_multiple_rules: true

  sources:
    - ansible.eda.pg_listener:
        pg_port: 5432

  rules:
    - name: Confirm CrashLoop rule matched
      condition: >-
        event.payload.alerts is defined and
        event.payload.status == "firing" and
        event.payload.alerts[0].status == "firing" and
        event.payload.alerts[0].labels.pod is defined and
        event.payload.alerts[0].labels.alertname == "PodCrashLooping"
        
      action:
        debug:
          msg:
            - "CrashLoop rule matched"
            - "Namespace: {{ event.payload.alerts[0].labels.namespace }}"
            - "Pod: {{ event.payload.alerts[0].labels.pod }}"

    - name: Launch gather logs workflow
      condition: >-
        event.payload.alerts is defined and
        event.payload.status == "firing" and
        event.payload.alerts[0].status == "firing" and
        event.payload.alerts[0].labels.alertname == "PodCrashLooping"
      action:
        run_workflow_template:
          name: gather_logs
          organization: Default
          job_args:
            extra_vars:
              namespace: "{{ event.payload.alerts[0].labels.namespace }}"
              pod_name: "{{ event.payload.alerts[0].labels.pod }}"
              alert_name: "{{ event.payload.alerts[0].labels.alertname }}"
